version: '3.7'

services:
# ==================================
# Data Loader
# ==================================
  data_loader:
    image: yts_base
    environment:
      - PYTHONPATH=/platform/libraries
    working_dir: /platform/data_loader
    command: python3 -u load_data.py
    volumes:
      - /home/helios/Desktop/fampay_ytsearch:/platform
    container_name: data_loader
    network_mode: "host"
