version: '3.7'

services:
# ==================================
# RethinkDB Database
# ==================================
  realtime_database:
    image: rethinkdb
    container_name: realtime_database
    network_mode: "host"

# ==================================
# Data Loader
# ==================================
  data_loader:
    image: platform-base
    environment:
      - PYTHONPATH=/app
    working_dir: /app/data_loader
    command: python3 -u load_data.py
    container_name: data_loader
    depends_on:
      - realtime_database
    network_mode: "host"

# ==================================
# AIOHTTP REST Server
# ==================================
  rest_server:
    image: platform-base
    environment:
      - PYTHONPATH=/app
    working_dir: /app/rest_server
    command: python3 -u main.py
    container_name: rest_server
    depends_on:
      - realtime_database, data_loader
    network_mode: "host"